---

antora:
  name: modules
  dir: www
  modules:
    - name: index
      label: Module 1
    - name: module-02
      label: Module 2
    - name: module-03
      label: Module 3
    - name: module-04
      label: Module 4
    - name: module-05
      label: Module 5
tabs:
  - name: ">_ Root"
    port: 443
    path: /wetty
    user: root
    host: rhel
    type: tty
  - name: ">_ rhel"
    port: 443
    path: /wetty
  - name: "Cockpit"
    port: 9943
    path: "/cockpit"
