---

antora:
  name: modules
  dir: www
  modules:
    - name: index
      label: Accessing documentation using man
    - name: module-02
      label: What is the ~ directory?
    - name: module-03
      label: Accessing Hidden Files
    - name: module-04
      label: Running commands as root vs using sudo
    - name: module-05
      label: Date and Time
tabs:
  - name: ">_ root"
    port: 443
    path: /tty1
    user: root
    host: rhel
  - name: ">_ rhel"
    port: 443
    path: /tty2
    user: rhel
    host: rhel
